sudo: required
services:
  - docker

before_install:
  - docker build -t resurect/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true resurect/docker-react npm run test -- --coverage  

